name: Build and push arm64 images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to build the image with
        required: true
        type: string
        default: latest
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and push fastly exporter arm64 image
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    env:
      tag: ${{ inputs.tag || 'latest' }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          show-progress: false
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/alphagov/fastly-exporter:${{ env.tag }}
